name: Secret Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  secrets:
    uses: apidepth-io/apidepth-tooling/.github/workflows/secret-scan.yml@main
    secrets: inherit
