name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  security:
    uses: apidepth-io/apidepth-tooling/.github/workflows/security-ruby.yml@main
    with:
      run-brakeman: false
